// <copyright file="Program.cs" company="Codenized">
// Copyright (c) Codenized. All rights reserved.
// </copyright>

// <auto-generated>

using Codenized.Exceptions.GlobalExceptionStrategy;
using Codenized.Planixor.Services.Authentication;
using Codenized.Planixor.Api.Endpoints;
using Codenized.Planixor.Core.Settings;
using Codenized.Planixor.IoC;
using Codenized.Planixor.Persistence.IoC;
using Microsoft.AspNetCore.Authentication;
using Microsoft.Extensions.Options;
using Microsoft.OpenApi;

var builder = WebApplication.CreateBuilder(args);
builder.ConfigureApplication();
builder.Services.AddAuthentication("ApiKey")
    .AddScheme<AuthenticationSchemeOptions, ApiKeyAuthenticationHandler>("ApiKey", null);
builder.Services.AddAuthorization();
builder.Services.AddApiHealthChecks(builder.Configuration);
builder.Services.AddOpenApi(options =>
{
    options.AddDocumentTransformer((document, context, cancellationToken) =>
    {
        document.Info.Title = "Planixor API";
        document.Info.Version = "v1";

        document.Components ??= new OpenApiComponents();
        document.Components.SecuritySchemes ??= new Dictionary<string, IOpenApiSecurityScheme>();
        document.Components.SecuritySchemes["Bearer"] = new OpenApiSecurityScheme
        {
            Type = SecuritySchemeType.Http,
            Scheme = "bearer",
            BearerFormat = "API Key",
            Description = "Enter your API key (without the 'Bearer' prefix)",
        };

        document.Security ??= [];
        document.Security.Add(new OpenApiSecurityRequirement
        {
            [new OpenApiSecuritySchemeReference("Bearer", document)] = new List<string>(),
        });

        return Task.CompletedTask;
    });
});
builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
    {
        policy.AllowAnyMethod().AllowAnyHeader()
            .SetIsOriginAllowed(origin => true)
            .AllowCredentials()
            .SetPreflightMaxAge(TimeSpan.FromHours(1));
    });
});
builder.Services.ConfigureHttpJsonOptions(options =>
{
    options.SerializerOptions.PropertyNamingPolicy = System.Text.Json.JsonNamingPolicy.CamelCase;
    options.SerializerOptions.DictionaryKeyPolicy = System.Text.Json.JsonNamingPolicy.CamelCase;
    options.SerializerOptions.DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull;
    options.SerializerOptions.NumberHandling = System.Text.Json.Serialization.JsonNumberHandling.AllowReadingFromString;
    options.SerializerOptions.PropertyNameCaseInsensitive = true;
    options.SerializerOptions.Converters.Add(new System.Text.Json.Serialization.JsonStringEnumConverter());
    options.SerializerOptions.WriteIndented = false;
    options.SerializerOptions.MaxDepth = 32;
    options.SerializerOptions.AllowTrailingCommas = true;
    options.SerializerOptions.ReadCommentHandling = System.Text.Json.JsonCommentHandling.Skip;
});

var app = builder.Build();
var settings = app.Services.GetService<IOptions<AppSettings>>()?.Value ?? throw new InvalidOperationException($"{nameof(AppSettings)} not found");
app.UseApiGlobalExceptionStrategy();
app.UseAuthentication();
app.UseAuthorization();
app.UseApplicationMigrations();
app.UseHttpsRedirection();
app.UseCors();

if (settings.AllowSwagger)
{
    var openApiEndpoint = $"{settings.ApiBasePath}/openapi.json";
    app.MapOpenApi(openApiEndpoint).AllowAnonymous();
    app.UseSwaggerUI(options =>
    {
        options.SwaggerEndpoint($"../../{openApiEndpoint.TrimStart('/')}", $"{settings.Product}-{settings.Service}");
        options.RoutePrefix = settings.ApiBasePath.TrimStart('/') + "/swagger";
    });
}

app.UseAppEndpoints(app.Configuration, settings.ApiBasePath);
await app.RunAsync();
