// <copyright file="Program.cs" company="Codenized">
// Copyright (c) Codenized. All rights reserved.
// </copyright>

// <auto-generated>

using Codenized.Exceptions.GlobalExceptionStrategy;
using Codenized.Planixor.Services.Authentication;
using Codenized.Planixor.Api.Endpoints;
using Codenized.Planixor.Core.Settings;
using Codenized.Planixor.IoC;
using Codenized.Planixor.Persistence.IoC;
using Codenized.Security.RateLimit;
using Microsoft.AspNetCore.Authentication;
using Microsoft.Extensions.Options;
using Microsoft.OpenApi;

var builder = WebApplication.CreateBuilder(args);
builder.ConfigureApplication();
builder.Services.AddAuthentication("ApiKey")
    .AddScheme<AuthenticationSchemeOptions, ApiKeyAuthenticationHandler>("ApiKey", null);
builder.Services.AddAuthorization();
builder.Services.AddApiHealthChecks(builder.Configuration);
builder.Services.AddOpenApi(options =>
{
    options.AddDocumentTransformer((document, context, cancellationToken) =>
    {
        document.Info.Title = "Planixor API";
        document.Info.Version = "v1";

        document.Components ??= new OpenApiComponents();
        document.Components.SecuritySchemes ??= new Dictionary<string, IOpenApiSecurityScheme>();
        document.Components.SecuritySchemes["Bearer"] = new OpenApiSecurityScheme
        {
            Type = SecuritySchemeType.Http,
            Scheme = "bearer",
            BearerFormat = "API Key",
            Description = "Enter your API key (without the 'Bearer' prefix)",
        };

        document.Security ??= [];
        document.Security.Add(new OpenApiSecurityRequirement
        {
            [new OpenApiSecuritySchemeReference("Bearer", document)] = new List<string>(),
        });

        return Task.CompletedTask;
    });
});
builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
    {
        // No AllowCredentials: authentication travels in an explicit Authorization header, which CORS does not
        // treat as a credential, so the API never needs the browser to attach ambient cookies. Combined with
        // AllowAnyOrigin — which emits "*" instead of reflecting the caller's origin — the browser refuses to
        // send credentials even if a page asks it to.
        policy.AllowAnyOrigin()
            .AllowAnyMethod()
            .AllowAnyHeader()
            .SetPreflightMaxAge(TimeSpan.FromHours(1));
    });
});
builder.Services.AddCodenizedRateLimit(builder.Configuration);

builder.Services.ConfigureHttpJsonOptions(options =>
{
    options.SerializerOptions.PropertyNamingPolicy = System.Text.Json.JsonNamingPolicy.CamelCase;
    options.SerializerOptions.DictionaryKeyPolicy = System.Text.Json.JsonNamingPolicy.CamelCase;
    options.SerializerOptions.DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull;
    options.SerializerOptions.NumberHandling = System.Text.Json.Serialization.JsonNumberHandling.AllowReadingFromString;
    options.SerializerOptions.PropertyNameCaseInsensitive = true;
    options.SerializerOptions.Converters.Add(new System.Text.Json.Serialization.JsonStringEnumConverter());
    options.SerializerOptions.WriteIndented = false;
    options.SerializerOptions.MaxDepth = 32;
    options.SerializerOptions.AllowTrailingCommas = true;
    options.SerializerOptions.ReadCommentHandling = System.Text.Json.JsonCommentHandling.Skip;
});

var app = builder.Build();
var settings = app.Services.GetService<IOptions<AppSettings>>()?.Value ?? throw new InvalidOperationException($"{nameof(AppSettings)} not found");
// Migrations are a start-up step, not middleware: run them before the pipeline serves anything.
app.UseApplicationMigrations();

app.UseApiGlobalExceptionStrategy(app.Environment.IsDevelopment());
app.UseHttpsRedirection();

// CORS goes ahead of the rate limiter and of authentication, which is the order ASP.NET documents and the reason
// error responses carry CORS headers at all. It used to be registered last, after authentication — and since the
// authentication handler signals failure by throwing, the global handler caught it above CORS and the response went
// out with no CORS headers. A browser client saw "TypeError: Failed to fetch" instead of the ProblemDetails the
// server had carefully built, so every 400, 401 and 429 was invisible in the web app.
app.UseCors();

// The rate limiter stays ahead of authentication on purpose: an invalid key must be counted before the
// authentication handler gets a chance to reject it, or a brute-force attempt would never be limited.
app.UseRateLimiter();

app.UseAuthentication();
app.UseAuthorization();

if (settings.AllowSwagger)
{
    var openApiEndpoint = $"{settings.ApiBasePath}/openapi.json";
    app.MapOpenApi(openApiEndpoint).AllowAnonymous();
    app.UseSwaggerUI(options =>
    {
        options.SwaggerEndpoint($"../../{openApiEndpoint.TrimStart('/')}", $"{settings.Product}-{settings.Service}");
        options.RoutePrefix = settings.ApiBasePath.TrimStart('/') + "/swagger";
    });
}

app.UseAppEndpoints(app.Configuration, settings.ApiBasePath);
await app.RunAsync();
