// <copyright file="Program.cs" company="Codenized">
// Copyright (c) Codenized. All rights reserved.
// </copyright>

// <auto-generated>

using Codenized.Exceptions.GlobalExceptionStrategy;
using Codenized.Planixor.Api.Endpoints;
using Codenized.Planixor.Core.Settings;
using Codenized.Planixor.IoC;
using Codenized.Planixor.Persistence.IoC;
using Microsoft.Extensions.Options;

var builder = WebApplication.CreateBuilder(args);
builder.ConfigureApplication();
builder.Services.AddApiHealthChecks(builder.Configuration);
builder.Services.AddOpenApi();
builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
    {
        policy.AllowAnyMethod().AllowAnyHeader()
            .SetIsOriginAllowed(origin => true)
            .AllowCredentials()
            .SetPreflightMaxAge(TimeSpan.FromHours(1));
    });
});
builder.Services.ConfigureHttpJsonOptions(options =>
{
    options.SerializerOptions.PropertyNamingPolicy = System.Text.Json.JsonNamingPolicy.CamelCase;
    options.SerializerOptions.DictionaryKeyPolicy = System.Text.Json.JsonNamingPolicy.CamelCase;
    options.SerializerOptions.DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull;
    options.SerializerOptions.NumberHandling = System.Text.Json.Serialization.JsonNumberHandling.AllowReadingFromString;
    options.SerializerOptions.PropertyNameCaseInsensitive = true;
    options.SerializerOptions.Converters.Add(new System.Text.Json.Serialization.JsonStringEnumConverter());
    options.SerializerOptions.WriteIndented = false;
    options.SerializerOptions.MaxDepth = 32;
    options.SerializerOptions.AllowTrailingCommas = true;
    options.SerializerOptions.ReadCommentHandling = System.Text.Json.JsonCommentHandling.Skip;
});

var app = builder.Build();
var settings = app.Services.GetService<IOptions<AppSettings>>()?.Value ?? throw new InvalidOperationException($"{nameof(AppSettings)} not found");
app.UseApiGlobalExceptionStrategy();
app.UseApplicationMigrations();
app.UseHttpsRedirection();
app.UseCors();

if (settings.AllowSwagger)
{
    var openApiEndpoint = $"{settings.ApiBasePath}/openapi.json";
    app.MapOpenApi(openApiEndpoint);
    app.UseSwaggerUI(options =>
    {
        options.SwaggerEndpoint($"../../{openApiEndpoint.TrimStart('/')}", $"{settings.Product}-{settings.Service}");
        options.RoutePrefix = settings.ApiBasePath.TrimStart('/') + "/swagger";
    });
}

app.UseAppEndpoints(app.Configuration, settings.ApiBasePath);
await app.RunAsync();
