// <auto-generated />
using System;
using Codenized.Planixor.Persistence.MySql.Efc.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Codenized.Planixor.Persistence.MySql.Efc.DataContext.Migrations
{
    [DbContext(typeof(MigrationContext))]
    [Migration("20260615083428_AddShift")]
    partial class AddShift
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Codenized.Planixor.Core.Entities.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Shifts_UserId");

                    b.HasIndex("UserId", "ModifiedAt")
                        .HasDatabaseName("IX_Shifts_UserId_ModifiedAt");

                    b.ToTable("Shifts", (string)null);
                });

            modelBuilder.Entity("Codenized.Planixor.Core.Entities.Shift", b =>
                {
                    b.OwnsOne("Codenized.Planixor.Core.ValueObjects.ShiftTime", "EndTime", b1 =>
                        {
                            b1.Property<Guid>("ShiftId")
                                .HasColumnType("char(36)");

                            b1.Property<int>("TotalMinutes")
                                .HasColumnType("int")
                                .HasColumnName("EndTime");

                            b1.HasKey("ShiftId");

                            b1.ToTable("Shifts");

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.OwnsOne("Codenized.Planixor.Core.ValueObjects.ShiftTime", "StartTime", b1 =>
                        {
                            b1.Property<Guid>("ShiftId")
                                .HasColumnType("char(36)");

                            b1.Property<int>("TotalMinutes")
                                .HasColumnType("int")
                                .HasColumnName("StartTime");

                            b1.HasKey("ShiftId");

                            b1.ToTable("Shifts");

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.OwnsOne("Codenized.Planixor.Core.ValueObjects.HoursWorked", "HoursWorked", b1 =>
                        {
                            b1.Property<Guid>("ShiftId")
                                .HasColumnType("char(36)");

                            b1.Property<int>("TotalMinutes")
                                .HasColumnType("int")
                                .HasColumnName("HoursWorked");

                            b1.HasKey("ShiftId");

                            b1.ToTable("Shifts");

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.OwnsOne("Codenized.Planixor.Core.ValueObjects.ShiftColor", "BackgroundColor", b1 =>
                        {
                            b1.Property<Guid>("ShiftId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar(7)")
                                .HasColumnName("BackgroundColor");

                            b1.HasKey("ShiftId");

                            b1.ToTable("Shifts");

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.OwnsOne("Codenized.Planixor.Core.ValueObjects.ShiftIcon", "Icon", b1 =>
                        {
                            b1.Property<Guid>("ShiftId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar(10)")
                                .HasColumnName("Icon");

                            b1.HasKey("ShiftId");

                            b1.ToTable("Shifts");

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.OwnsOne("Codenized.Planixor.Core.ValueObjects.ShiftName", "Name", b1 =>
                        {
                            b1.Property<Guid>("ShiftId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasColumnName("Name");

                            b1.HasKey("ShiftId");

                            b1.ToTable("Shifts");

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.Navigation("BackgroundColor")
                        .IsRequired();

                    b.Navigation("EndTime")
                        .IsRequired();

                    b.Navigation("HoursWorked")
                        .IsRequired();

                    b.Navigation("Icon")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("StartTime")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
