// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Codenized.Planixor.Persistence.MySql.Efc.DataContext.Migrations
{
    /// <inheritdoc />
    public partial class MigrateCalendarEventToMultiDay : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE `CalendarEvents` DROP CHECK `CK_CalendarEvents_EndTimeAfterStartTime`;");

            migrationBuilder.DropIndex(
                name: "IX_CalendarEvents_Day",
                table: "CalendarEvents");

            migrationBuilder.Sql("ALTER TABLE `CalendarEvents` RENAME COLUMN `Day` TO `StartDay`;");

            migrationBuilder.Sql("ALTER TABLE `CalendarEvents` ADD COLUMN `EndDay` date NOT NULL DEFAULT '0001-01-01';");
            migrationBuilder.Sql("UPDATE `CalendarEvents` SET `EndDay` = `StartDay`;");
            migrationBuilder.Sql("ALTER TABLE `CalendarEvents` ALTER COLUMN `EndDay` DROP DEFAULT;");

            migrationBuilder.AddColumn<int>(
                name: "TotalHours",
                table: "CalendarEvents",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AlterColumn<string>(
                name: "Notes",
                table: "CalendarEvents",
                type: "varchar(250)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "varchar(200)",
                oldNullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_CalendarEvents_StartDay",
                table: "CalendarEvents",
                column: "StartDay");

            migrationBuilder.CreateIndex(
                name: "IX_CalendarEvents_EndDay",
                table: "CalendarEvents",
                column: "EndDay");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_CalendarEvents_StartDay",
                table: "CalendarEvents");

            migrationBuilder.DropIndex(
                name: "IX_CalendarEvents_EndDay",
                table: "CalendarEvents");

            migrationBuilder.DropColumn(
                name: "EndDay",
                table: "CalendarEvents");

            migrationBuilder.DropColumn(
                name: "TotalHours",
                table: "CalendarEvents");

            migrationBuilder.Sql("ALTER TABLE `CalendarEvents` RENAME COLUMN `StartDay` TO `Day`;");

            migrationBuilder.AlterColumn<string>(
                name: "Notes",
                table: "CalendarEvents",
                type: "varchar(200)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "varchar(250)",
                oldNullable: true);

            migrationBuilder.AddCheckConstraint(
                name: "CK_CalendarEvents_EndTimeAfterStartTime",
                table: "CalendarEvents",
                sql: "EndTime > StartTime");

            migrationBuilder.CreateIndex(
                name: "IX_CalendarEvents_Day",
                table: "CalendarEvents",
                column: "Day");
        }
    }
}
