// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Codenized.Planixor.Persistence.MySql.Efc.DataContext.Migrations
{
    /// <inheritdoc />
    public partial class MigrateCalendarEventToMultiDay : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropCheckConstraint(
                name: "CK_CalendarEvents_EndTimeAfterStartTime",
                table: "CalendarEvents");

            migrationBuilder.DropIndex(
                name: "IX_CalendarEvents_Day",
                table: "CalendarEvents");

            migrationBuilder.RenameColumn(
                name: "Day",
                table: "CalendarEvents",
                newName: "StartDay");

            migrationBuilder.AddColumn<DateOnly>(
                name: "EndDay",
                table: "CalendarEvents",
                type: "date",
                nullable: false,
                defaultValue: new DateOnly(1, 1, 1));

            migrationBuilder.AddColumn<int>(
                name: "TotalHours",
                table: "CalendarEvents",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AlterColumn<string>(
                name: "Notes",
                table: "CalendarEvents",
                type: "varchar(250)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "varchar(200)",
                oldNullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_CalendarEvents_StartDay",
                table: "CalendarEvents",
                column: "StartDay");

            migrationBuilder.CreateIndex(
                name: "IX_CalendarEvents_EndDay",
                table: "CalendarEvents",
                column: "EndDay");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_CalendarEvents_StartDay",
                table: "CalendarEvents");

            migrationBuilder.DropIndex(
                name: "IX_CalendarEvents_EndDay",
                table: "CalendarEvents");

            migrationBuilder.DropColumn(
                name: "EndDay",
                table: "CalendarEvents");

            migrationBuilder.DropColumn(
                name: "TotalHours",
                table: "CalendarEvents");

            migrationBuilder.RenameColumn(
                name: "StartDay",
                table: "CalendarEvents",
                newName: "Day");

            migrationBuilder.AlterColumn<string>(
                name: "Notes",
                table: "CalendarEvents",
                type: "varchar(200)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "varchar(250)",
                oldNullable: true);

            migrationBuilder.AddCheckConstraint(
                name: "CK_CalendarEvents_EndTimeAfterStartTime",
                table: "CalendarEvents",
                sql: "EndTime > StartTime");

            migrationBuilder.CreateIndex(
                name: "IX_CalendarEvents_Day",
                table: "CalendarEvents",
                column: "Day");
        }
    }
}
