// <copyright file="OneTypePerFileScanner.cs" company="Codenized">
// Copyright (c) Codenized. All rights reserved.
// </copyright>

namespace UnitTest.Codenized.Planixor;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

/// <summary>
/// Counts the type declarations in a source tree, at any nesting depth.
/// </summary>
internal static class OneTypePerFileScanner
{
    /// <summary>
    /// Finds every file that declares more than one type.
    /// </summary>
    /// <param name="sourceRoot">The directory to walk.</param>
    /// <returns>One line per offending file, naming the types it declares.</returns>
    internal static List<string> Scan(string sourceRoot)
    {
        var violations = new List<string>();

        foreach (string file in SourceFiles(sourceRoot))
        {
            List<string> names = TypeNames(File.ReadAllText(file));

            if (names.Count > 1)
            {
                violations.Add($"  {Path.GetRelativePath(sourceRoot, file)} — {names.Count}: {string.Join(", ", names)}");
            }
        }

        violations.Sort(StringComparer.Ordinal);

        return violations;
    }

    /// <summary>Counts the type declarations in a source text.</summary>
    /// <param name="source">The source text.</param>
    /// <returns>The number of declared types, nested ones included.</returns>
    internal static int CountTypes(string source) => TypeNames(source).Count;

    /// <summary>Counts the files a scan would inspect.</summary>
    /// <param name="sourceRoot">The directory to walk.</param>
    /// <returns>The number of files inspected.</returns>
    internal static int CountScannedFiles(string sourceRoot) => SourceFiles(sourceRoot).Count();

    private static IEnumerable<string> SourceFiles(string sourceRoot) =>
        Directory.EnumerateFiles(sourceRoot, "*.cs", SearchOption.AllDirectories)
            .Where(f => !IsUnderExcludedDirectory(f))
            .Where(f => !IsGenerated(f));

    private static bool IsUnderExcludedDirectory(string file)
    {
        string[] segments = file.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);

        // Migrations are written by EF, not by a person, and the tool decides their shape.
        return segments.Contains("obj") || segments.Contains("bin") || segments.Contains("Migrations");
    }

    private static bool IsGenerated(string file)
    {
        using var reader = new StreamReader(file);

        for (int i = 0; i < 3; i++)
        {
            string? line = reader.ReadLine();

            if (line is null)
            {
                return false;
            }

            if (line.Contains("<auto-generated", StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static List<string> TypeNames(string source)
    {
        SyntaxNode root = CSharpSyntaxTree.ParseText(source).GetRoot();

        // BaseTypeDeclarationSyntax covers class, struct, record, interface and enum; delegates are a separate node
        // and are declarations of a type just the same.
        return root.DescendantNodes()
            .Where(n => n is BaseTypeDeclarationSyntax or DelegateDeclarationSyntax)
            .Select(n => n switch
            {
                BaseTypeDeclarationSyntax type => type.Identifier.ValueText,
                DelegateDeclarationSyntax d => d.Identifier.ValueText,
                _ => string.Empty,
            })
            .ToList();
    }
}
